
import { PortfolioItem } from './types';

export const MY_WORKS_DATA: PortfolioItem[] = [
  // --- IMAGE CATEGORY ---
  { id: 'img-001', category: 'Image', title: 'Studio Capture', image: 'https://i.ibb.co/N26KwTBX/0-B3-F2-C87-BC86-4-C76-9749-617-C6-FDFBF46.jpg' },
  { id: 'img-002', category: 'Image', title: 'Portrait Study', image: 'https://i.ibb.co/VWjSF6y5/0N4A2915.jpg' },
  { id: 'img-003', category: 'Image', title: 'Lighting Session', image: 'https://i.ibb.co/7tRWwVXC/0N4A2989.jpg' },
  { id: 'img-004', category: 'Image', title: 'Creative Shot', image: 'https://i.ibb.co/sp6PXMv9/1-A9-E50-C0-8-CA9-4-F83-80-C0-A9-E99547-FEB4.jpg' },
  { id: 'img-005', category: 'Image', title: 'Cinematic View', image: 'https://i.ibb.co/5XtqMsjw/03-D6-DD61-FAD9-4062-AEA6-20657-E2723-D8.jpg' },
  { id: 'img-006', category: 'Image', title: 'Dynamic Frame', image: 'https://i.ibb.co/Kp6vfdbN/4-A9-C5705-B81-A-4-C50-AFA6-C7-D1786977-C5.jpg' },
  { id: 'img-007', category: 'Image', title: 'Visual Contrast', image: 'https://i.ibb.co/sd1Z3Crs/5-DCDCD6-A-0330-4798-B1-A9-79-ECDBCB44-B8.jpg' },
  { id: 'img-008', category: 'Image', title: 'Mood Capture', image: 'https://i.ibb.co/Vpkvv9FY/6-F58-C55-D-495-B-47-CC-AB87-EC260-EA10528.jpg' },
  { id: 'img-009', category: 'Image', title: 'Detail Focus', image: 'https://i.ibb.co/9mgmfKjY/6-F1389-B1-434-E-45-B2-A4-B7-F016-DA0-E2-CAE-2.jpg' },
  { id: 'img-010', category: 'Image', title: 'Composition', image: 'https://i.ibb.co/84zF0R9R/9-ADC3-ECD-C747-4-B06-A56-D-DDC85-D6-E2-C80.jpg' },
  { id: 'img-011', category: 'Image', title: 'Fine Art Edit', image: 'https://i.ibb.co/qL6ZKLgC/19-C03-B54-5-F61-4136-B900-22-F95-E0-D2221.jpg' },
  { id: 'img-012', category: 'Image', title: 'Studio Depth', image: 'https://i.ibb.co/Vc0DdgbG/25-FD3-A96-3-AD6-4-A8-A-B80-C-6-FE764-C1-B79-D.jpg' },
  { id: 'img-013', category: 'Image', title: 'Minimalist Shot', image: 'https://i.ibb.co/Gv3XVrJq/35-A3082-D-00-CD-4060-964-F-230436312-BD2.jpg' },
  { id: 'img-014', category: 'Image', title: 'Lighting Art', image: 'https://i.ibb.co/M5Brq83p/37-DB3-D2-F-48-C0-42-B3-BC2-D-D438432-FF2-A9.jpg' },
  { id: 'img-015', category: 'Image', title: 'Profile Art', image: 'https://i.ibb.co/qMLfXLfX/90-B68052-077-F-4-C07-B8-E9-3-D613-EC33-FC2.jpg' },
  { id: 'img-016', category: 'Image', title: 'Abstract Capture', image: 'https://i.ibb.co/GQd6MrSw/337-CAE72-D74-E-40-CE-9-A8-A-D28-B3-AD397-A7.jpg' },
  { id: 'img-017', category: 'Image', title: 'Classic Frame', image: 'https://i.ibb.co/cckdf6R3/444-B802-C-6-BC2-4641-9623-5-C6-D9-AD22130.jpg' },
  { id: 'img-018', category: 'Image', title: 'Editorial Look', image: 'https://i.ibb.co/9HzDpbsL/1349-F69-C-F9-D7-4-BED-8-F9-F-C985-FD3-BB45-A.jpg' },
  { id: 'img-019', category: 'Image', title: 'Visual Depth', image: 'https://i.ibb.co/cSTmgg0s/2360-BED7-DD3-E-4-D96-BA8-E-F106-DF01-FB7-E.jpg' },
  { id: 'img-020', category: 'Image', title: 'Professional Work', image: 'https://i.ibb.co/p6dNyhk8/3005-F96-A-06-DE-46-BB-956-A-45-D1-C8-F4-DF93.jpg' },

  // --- LOGO CATEGORY (23 LOGOS) ---
  { id: 'logo-01', category: 'Logo', title: 'Logo Design 01', image: 'https://i.ibb.co/VcwC3jGq/01.png', isLogo: true },
  { id: 'logo-02', category: 'Logo', title: 'Logo Design 02', image: 'https://i.ibb.co/vv1kQshS/2.png', isLogo: true },
  { id: 'logo-03', category: 'Logo', title: 'Logo Design 03', image: 'https://i.ibb.co/V09zGDnM/03.png', isLogo: true },
  { id: 'logo-04', category: 'Logo', title: 'Logo Design 04', image: 'https://i.ibb.co/23SQ8yHD/04.png', isLogo: true },
  { id: 'logo-05', category: 'Logo', title: 'Logo Design 05', image: 'https://i.ibb.co/0y1t1M76/05.png', isLogo: true },
  { id: 'logo-06', category: 'Logo', title: 'Logo Design 06', image: 'https://i.ibb.co/KzhggxQj/06.png', isLogo: true },
  { id: 'logo-07', category: 'Logo', title: 'Logo Design 07', image: 'https://i.ibb.co/1Jv1pYky/07.png', isLogo: true },
  { id: 'logo-08', category: 'Logo', title: 'Logo Design 08', image: 'https://i.ibb.co/207tzmYC/08.png', isLogo: true },
  { id: 'logo-09', category: 'Logo', title: 'Logo Design 09', image: 'https://i.ibb.co/9kBn8Cgm/09.png', isLogo: true },
  { id: 'logo-10', category: 'Logo', title: 'Logo Design 10', image: 'https://i.ibb.co/FQLHFzT/10.png', isLogo: true },
  { id: 'logo-11', category: 'Logo', title: 'Logo Design 11', image: 'https://i.ibb.co/XZLrzJP0/11.png', isLogo: true },
  { id: 'logo-12', category: 'Logo', title: 'Logo Design 12', image: 'https://i.ibb.co/VWWVRdDG/12.png', isLogo: true },
  { id: 'logo-13', category: 'Logo', title: 'Logo Design 13', image: 'https://i.ibb.co/pBkNd1p4/13.png', isLogo: true },
  { id: 'logo-14', category: 'Logo', title: 'Logo Design 14', image: 'https://i.ibb.co/RkB6LLCv/14.png', isLogo: true },
  { id: 'logo-15', category: 'Logo', title: 'Logo Design 15', image: 'https://i.ibb.co/Jwn4NYJ2/15.png', isLogo: true },
  { id: 'logo-16', category: 'Logo', title: 'Logo Design 16', image: 'https://i.ibb.co/nM0cm3kr/16.png', isLogo: true },
  { id: 'logo-17', category: 'Logo', title: 'Logo Design 17', image: 'https://i.ibb.co/XZgCVHPR/17.png', isLogo: true },
  { id: 'logo-18', category: 'Logo', title: 'Logo Design 18', image: 'https://i.ibb.co/R4hNfzC6/18.png', isLogo: true },
  { id: 'logo-19', category: 'Logo', title: 'Logo Design 19', image: 'https://i.ibb.co/qLv1RTSP/19.png', isLogo: true },
  { id: 'logo-20', category: 'Logo', title: 'Logo Design 20', image: 'https://i.ibb.co/35dckJ1p/20.png', isLogo: true },
  { id: 'logo-21', category: 'Logo', title: 'Logo Design 21', image: 'https://i.ibb.co/HD0ppgzF/21.png', isLogo: true },
  { id: 'logo-22', category: 'Logo', title: 'Logo Design 22', image: 'https://i.ibb.co/cSxcvPVg/22.png', isLogo: true },
  { id: 'logo-23', category: 'Logo', title: 'Logo Design 23', image: 'https://i.ibb.co/LDsJHG7G/23.png', isLogo: true },

  // --- SOCIAL MEDIA CATEGORY ---
  { id: 'sm-001', category: 'Social Media', title: 'Social Design 1', image: 'https://i.ibb.co/3mxbcs4v/1-2.png' },
  { id: 'sm-002', category: 'Social Media', title: 'Social Design 2', image: 'https://i.ibb.co/cXNvs20L/2.png' },
  { id: 'sm-003', category: 'Social Media', title: 'Social Design 3', image: 'https://i.ibb.co/C5Vr2r3D/1-3.png' },
  { id: 'sm-004', category: 'Social Media', title: 'Social Design 4', image: 'https://i.ibb.co/MkxzYVQ6/3.png' },
  { id: 'sm-005', category: 'Social Media', title: 'Social Design 5', image: 'https://i.ibb.co/gLRP6Jtt/1-4-2.png' },
  { id: 'sm-006', category: 'Social Media', title: 'Social Design 6', image: 'https://i.ibb.co/zVc76J59/4-2.png' },
  { id: 'sm-007', category: 'Social Media', title: 'Social Design 7', image: 'https://i.ibb.co/C3FkQ7HS/1-4.png' },
  { id: 'sm-008', category: 'Social Media', title: 'Social Design 8', image: 'https://i.ibb.co/G4Tx9Sss/4.png' },
  { id: 'sm-009', category: 'Social Media', title: 'Social Design 9', image: 'https://i.ibb.co/xKDJrHb5/1-5.png' },
  { id: 'sm-010', category: 'Social Media', title: 'Social Design 10', image: 'https://i.ibb.co/0jQXrjCN/5.png' },
  { id: 'sm-011', category: 'Social Media', title: 'Social Design 11', image: 'https://i.ibb.co/x8BR4YSs/1-6.png' },
  { id: 'sm-012', category: 'Social Media', title: 'Social Design 12', image: 'https://i.ibb.co/JL6qf1g/6.png' },
  { id: 'sm-013', category: 'Social Media', title: 'Social Design 13', image: 'https://i.ibb.co/YTZhyqkS/1-7.png' },
  { id: 'sm-014', category: 'Social Media', title: 'Social Design 14', image: 'https://i.ibb.co/DDWmPtVG/7.png' },
  { id: 'sm-015', category: 'Social Media', title: 'Social Design 15', image: 'https://i.ibb.co/RmG10Dq/1-8.png' },
  { id: 'sm-016', category: 'Social Media', title: 'Social Design 16', image: 'https://i.ibb.co/MxttST1C/8.png' },
  { id: 'sm-017', category: 'Social Media', title: 'Social Design 17', image: 'https://i.ibb.co/fdyWFF9W/9.png' },
  { id: 'sm-018', category: 'Social Media', title: 'Social Design 18', image: 'https://i.ibb.co/qF9wYb4y/1.png' },

  // --- POSTERS CATEGORY (UPDATED 18 POSTERS) ---
  { id: 'ps-01', category: 'Posters', title: 'Visual Poster 01', image: 'https://i.ibb.co/h1sLk7gW/3-34.jpg' },
  { id: 'ps-02', category: 'Posters', title: 'Visual Poster 02', image: 'https://i.ibb.co/wFHXkwrD/897897.jpg' },
  { id: 'ps-03', category: 'Posters', title: 'Visual Poster 03', image: 'https://i.ibb.co/DfqJQNwN/2346534tygrdsg.jpg' },
  { id: 'ps-04', category: 'Posters', title: 'Visual Poster 04', image: 'https://i.ibb.co/qYW22KQZ/54754756.jpg' },
  { id: 'ps-05', category: 'Posters', title: 'Visual Poster 05', image: 'https://i.ibb.co/b5b4bvxG/2345425463.jpg' },
  { id: 'ps-06', category: 'Posters', title: 'Visual Poster 06', image: 'https://i.ibb.co/SXdkBT7B/kul.jpg' },
  { id: 'ps-07', category: 'Posters', title: 'Visual Poster 07', image: 'https://i.ibb.co/d4SXsX8B/Untitled-1.jpg' },
  { id: 'ps-08', category: 'Posters', title: 'Visual Poster 08', image: 'https://i.ibb.co/0VrG0C23/Untitled-2-3.jpg' },
  { id: 'ps-09', category: 'Posters', title: 'Visual Poster 09', image: 'https://i.ibb.co/d0pRPTM5/Untitled-3-Recovered.jpg' },
  { id: 'ps-10', category: 'Posters', title: 'Visual Poster 10', image: 'https://i.ibb.co/DSDDp5F/Untitled-256-2.jpg' },
  { id: 'ps-11', category: 'Posters', title: 'Visual Poster 11', image: 'https://i.ibb.co/V0Hw4kt8/Untitled-17986789.jpg' },
  { id: 'ps-12', category: 'Posters', title: 'Visual Poster 12', image: 'https://i.ibb.co/xt14ssKg/image.png' },
  { id: 'ps-13', category: 'Posters', title: 'Visual Poster 13', image: 'https://i.ibb.co/ymRn83mY/20.png' },
  { id: 'ps-14', category: 'Posters', title: 'Visual Poster 14', image: 'https://i.ibb.co/pvmc3jXX/10961106.png' },
  { id: 'ps-15', category: 'Posters', title: 'Visual Poster 15', image: 'https://i.ibb.co/DPFjGcfs/324152436-00000-2.png' },
  { id: 'ps-16', category: 'Posters', title: 'Visual Poster 16', image: 'https://i.ibb.co/S4L7zn9V/2-00000.png' },
  { id: 'ps-17', category: 'Posters', title: 'Visual Poster 17', image: 'https://i.ibb.co/1YM0mtyj/image.png' },
  { id: 'ps-18', category: 'Posters', title: 'Visual Poster 18', image: 'https://i.ibb.co/LhQcm8fT/Poster.png' },

  // --- BOOK COVERS CATEGORY ---
  { id: 'bc-01', category: 'Book Covers', title: 'Cover Design 1', image: 'https://i.ibb.co/tw5Hzfvy/3.jpg' },
  { id: 'bc-02', category: 'Book Covers', title: 'Cover Design 2', image: 'https://i.ibb.co/DfssV1zX/1-2.png' },

  // --- GENERAL DESIGN CATEGORY ---
  { id: 'gen-01', category: 'General Design', title: 'Composition Study', image: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&q=80&w=1200' },
  { id: 'gen-02', category: 'General Design', title: 'Symmetry Logic', image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&q=80&w=1200' },
];
